import type { Metadata } from "next";
import ExamplesClient from "./ExamplesClient";

export const metadata: Metadata = {
  title: "Examples | ReadmeGenAI",
  description:
    "Browse real GitHub README examples generated by ReadmeGenAI. See AI README output for Next.js apps, TypeScript libraries, Go backends, and more.",
  openGraph: {
    title: "Examples | ReadmeGenAI",
    description:
      "Browse real GitHub README examples generated by ReadmeGenAI. See AI README output for Next.js apps, TypeScript libraries, Go backends, and more.",
    url: "/examples",
  },
};

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: "https://readmegen-ai.vercel.app/",
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "Examples",
      item: "https://readmegen-ai.vercel.app/examples",
    },
  ],
};

export default function ExamplesPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <ExamplesClient />
    </>
  );
}
